import { useEffect, useState } from "react";

import {
  CreditCard,
  CheckCircle,
  AlertCircle,
  Wallet
} from "lucide-react";

import ResidentLayout from "../../components/layout/ResidentLayout";
import api from "../../api/axios";

export default function ResidentBills() {

  const [bills, setBills] = useState([]);

  const [loading, setLoading] = useState(true);

  const [selectedBill, setSelectedBill] = useState(null);

  const [paymentMethod, setPaymentMethod] =
    useState("UPI");

  useEffect(() => {
    fetchBills();
  }, []);

  // ================= FETCH BILLS =================

  const fetchBills = async () => {

    try {

      const res = await api.get("/bills");

      setBills(
        Array.isArray(res.data)
          ? res.data
          : []
      );

    } catch (err) {

      console.error(err);

    } finally {

      setLoading(false);

    }
  };

  // ================= PAY BILL =================

  const payBill = async () => {

    try {

      await api.patch(
        `/bills/${selectedBill._id}/pay`,
        {
          paymentMethod
        }
      );

      alert("Bill paid successfully");

      setSelectedBill(null);

      fetchBills();

    } catch (err) {

      alert(
        err.response?.data?.message ||
        "Payment failed"
      );

    }
  };

  // ================= STATS =================

  const paidBills = bills.filter(
    b => b.paid
  );

  const unpaidBills = bills.filter(
    b => !b.paid
  );

  const totalDue = unpaidBills.reduce(
    (sum, bill) => sum + bill.amount,
    0
  );

  return (

    <ResidentLayout>

      {/* HEADER */}

      <div className="mb-8">

        <h1 className="text-4xl font-bold">
          My Bills
        </h1>

        <p className="text-gray-500 mt-1">
          Manage your society maintenance payments
        </p>

      </div>

      {/* STATS */}

      <div className="grid md:grid-cols-4 gap-6 mb-8">

        <StatCard
          title="Total Bills"
          value={bills.length}
          color="bg-indigo-600"
          icon={<CreditCard />}
        />

        <StatCard
          title="Paid"
          value={paidBills.length}
          color="bg-green-600"
          icon={<CheckCircle />}
        />

        <StatCard
          title="Pending"
          value={unpaidBills.length}
          color="bg-red-500"
          icon={<AlertCircle />}
        />

        <StatCard
          title="Amount Due"
          value={`₹${totalDue}`}
          color="bg-orange-500"
          icon={<Wallet />}
        />

      </div>

      {/* BILLS */}

      <div className="space-y-6">

        {loading ? (

          <div className="bg-white rounded-3xl shadow-lg p-10 text-center">

            <p className="text-gray-500">
              Loading bills...
            </p>

          </div>

        ) : bills.length === 0 ? (

          <div className="bg-white rounded-3xl shadow-lg p-10 text-center">

            <CreditCard
              size={50}
              className="mx-auto text-gray-400 mb-4"
            />

            <h3 className="text-xl font-semibold mb-2">
              No Bills Found
            </h3>

            <p className="text-gray-500">
              You currently have no maintenance bills.
            </p>

          </div>

        ) : (

          bills.map(bill => (

            <div
              key={bill._id}
              className="bg-white rounded-3xl shadow-lg p-6 hover:shadow-2xl transition"
            >

              <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-5">

                {/* LEFT */}

                <div>

                  <h2 className="text-2xl font-bold mb-2">

                    ₹{bill.amount}

                  </h2>

                  <p className="text-gray-500 mb-1">

                    Due Date:{" "}

                    {new Date(
                      bill.dueDate
                    ).toLocaleDateString()}

                  </p>

                  <p className="text-gray-500">

                    Generated By:{" "}

                    {bill.generatedBy?.name ||
                      "Admin"}

                  </p>

                </div>

                {/* RIGHT */}

                <div className="flex flex-col items-start lg:items-end gap-4">

                  {bill.paid ? (

                    <>

                      <StatusBadge
                        status="PAID"
                      />

                      <div className="text-sm text-gray-500 text-right">

                        <p>

                          Paid On:{" "}

                          {bill.paymentDate
                            ? new Date(
                                bill.paymentDate
                              ).toLocaleDateString()
                            : "-"}

                        </p>

                        <p>

                          Method:{" "}

                          {bill.paymentMethod ||
                            "-"}

                        </p>

                      </div>

                    </>

                  ) : (

                    <>

                      <StatusBadge
                        status="PENDING"
                      />

                      <button
                        onClick={() =>
                          setSelectedBill(
                            bill
                          )
                        }
                        className="bg-indigo-600 hover:bg-indigo-700 text-white px-5 py-3 rounded-2xl font-semibold"
                      >
                        Pay Now
                      </button>

                    </>

                  )}

                </div>

              </div>

            </div>

          ))

        )}

      </div>

      {/* PAYMENT MODAL */}

      {selectedBill && (

        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4">

          <div className="bg-white rounded-3xl shadow-2xl w-full max-w-md p-8">

            <h2 className="text-3xl font-bold mb-6">

              Pay Bill

            </h2>

            <div className="mb-5">

              <p className="text-gray-500 mb-2">
                Amount
              </p>

              <h3 className="text-4xl font-bold">

                ₹{selectedBill.amount}

              </h3>

            </div>

            <div className="mb-6">

              <label className="block font-medium mb-2">

                Payment Method

              </label>

              <select
                value={paymentMethod}
                onChange={e =>
                  setPaymentMethod(
                    e.target.value
                  )
                }
                className="w-full border rounded-2xl p-4"
              >

                <option value="UPI">
                  UPI
                </option>

                <option value="CARD">
                  CARD
                </option>

                <option value="CASH">
                  CASH
                </option>

              </select>

            </div>

            <div className="flex gap-4">

              <button
                onClick={() =>
                  setSelectedBill(null)
                }
                className="flex-1 border rounded-2xl py-3 font-semibold hover:bg-gray-100"
              >
                Cancel
              </button>

              <button
                onClick={payBill}
                className="flex-1 bg-indigo-600 hover:bg-indigo-700 text-white rounded-2xl py-3 font-semibold"
              >
                Confirm Payment
              </button>

            </div>

          </div>

        </div>

      )}

    </ResidentLayout>

  );
}


// ================= STAT CARD =================

function StatCard({
  title,
  value,
  color,
  icon
}) {

  return (

    <div className="bg-white rounded-3xl shadow-lg p-6 flex items-center gap-5">

      <div className={`${color} text-white p-4 rounded-2xl`}>

        {icon}

      </div>

      <div>

        <p className="text-gray-500">
          {title}
        </p>

        <h2 className="text-3xl font-bold">
          {value}
        </h2>

      </div>

    </div>

  );
}


// ================= STATUS BADGE =================

function StatusBadge({
  status
}) {

  const styles = {

    PAID:
      "bg-green-100 text-green-700",

    PENDING:
      "bg-red-100 text-red-700"

  };

  return (

    <span
      className={`px-4 py-2 rounded-xl text-sm font-semibold ${styles[status]}`}
    >

      {status}

    </span>

  );
}